### ISSUE TITLE
Compute probability per point

### ISSUE THREAD

**Issue by JR9124** [sitzikbs/3DmFV-Tutorial#3]
hi, I have read the code in utils.py, but I am puzzled about probability computation in line 295 to 296. 
p_per_point = (1.0 / (np.power(2.0 * np.pi, D / 2.0) * np.power(batch_sig[:, :, :, 0], D))) * np.exp(
        -0.5 * np.sum(np.square((batch_points - batch_mu) / batch_sig), axis=3))
Why the item-np.power(batch_sig[:, :, :, 0], D)- is multiplied? I don't know why the first axis and D are used, could you help me?

**Comment by sitzikbs** [comment]
In the Arxiv version of the paper, see section 3.1,  Equation 1.

**Comment by hehe549124** [comment]
Actually, I have read your paper released in IEEE ROBOTICS AND AUTOMATION LETTERS. However, I still don't understand the meaning of np.power(batch_sig[:, :, :, 0], D) after I read Equation 1 in section 3.1, it doesn't stand for sqrt(delta(sigma)) as only variance of the first Gaussian is used in np.power(batch_sig[:, :, :, 0], D), could you give me more help?
![image](https://user-images.githubusercontent.com/17962615/58960406-b7093e00-87d9-11e9-9388-b3e9bf819fe5.png)
