### ISSUE TITLE
puzzle about np.power(batch_sig[:, :, :, 0], D)

### ISSUE THREAD

**Issue by JR9124** [sitzikbs/3DmFV-Tutorial#4]
Thanks for your quickly reply. Actually, I have read your paper released in IEEE ROBOTICS AND AUTOMATION LETTERS. However, I still don't understand the meaning of np.power(batch_sig[:, :, :, 0], D) after I read Equation 1 in section 3.1, it doesn't stand for sqrt(delta(sigma)) as only variance of the first variable in Gaussian is used in np.power(batch_sig[:, :, :, 0], D), could you give me more help?Thank you!
![搜狗截图20190606060018](https://user-images.githubusercontent.com/17962615/58993775-13dc1700-8821-11e9-8631-e9ced4931930.png)

**Comment by sitzikbs** [comment]
Yes, you are correct. This is because the GMM is uniform (spherical -> Sigma matrix is diagonal, and all elements of the diagonal are the same). In addition, the weight for all Gaussians is the same as well).

**Comment by JR9124** [comment]
Thanks for your kindly help!
