### ISSUE TITLE
Typo in visualization code 

### ISSUE THREAD

**Issue by Theigrams** [sitzikbs/3DmFV-Tutorial#5]
https://github.com/sitzikbs/3DmFV-Tutorial/blob/ef5d35cac8a5885db34a3abe3131810ef172d265/visualization.py#L57

I think the right code may be:
```python
    derivatives = [r"$\max{g_{\alpha}}$",r"$\sum g_{\alpha}$",
```
Isn't it?

**Comment by sitzikbs** [comment]
Correct. Fixed.
